apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
    lang: java
spec:
  selector:
    matchLabels:
      app: customer
      lang: java
  template:
    metadata:
      name: customer-pod
      labels:
        lang: java
        app: customer
    spec:
      containers:
        - name: customer-container
          image: harinvb/customer:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.3"
              memory: "256M"
            limits:
              cpu: "0.5"
              memory: "300M"
          ports:
            - containerPort: 8080
              name: tcp8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-creds
  strategy:
    rollingUpdate:
      maxUnavailable: 35
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
    lang: java
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: tcp8080
      appProtocol: HTTP
  selector:
    app: customer
    lang: java
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customer-scaler
spec:
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer
  minReplicas: 2
  targetCPUUtilizationPercentage: 30
---
