apiVersion: v1
data:
  .dockerconfigjson: #{DOCKER_CONFIG}#
kind: Secret
metadata:
  name: docker-creds
  namespace: default
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
    lang: java
spec:
  selector:
    matchLabels:
      app: customer
      lang: java
  template:
    metadata:
      name: customer
      labels:
        lang: java
        app: customer
    spec:
      containers:
        - name: customer-container
          imagePullPolicy: IfNotPresent
          image: harinvb/customer:#{TAG}#
          resources:
            requests:
              cpu: "0.5"
              memory: "256M"
            limits:
              cpu: "0.7"
              memory: "300M"
          livenessProbe:

          ports:
            - containerPort: 8080
              name: tcp8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-creds

  strategy:
    rollingUpdate:
      maxUnavailable: 35
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
    lang: java
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: tcp8080
      appProtocol: HTTP
  selector:
    app: customer
    lang: java
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customer
  labels:
    app: customer
    lang: java
spec:
  maxReplicas: 3
  scaleTargetRef:
    kind: Deployment
    name: customer
  minReplicas: 1
  targetCPUUtilizationPercentage: 65
---
